# ███╗░░██╗██████╗░░█████╗░██╗██╗░░░░░██╗░░░██╗██████╗░███████╗░██╗░░░░░░░██╗░█████╗░██████╗░██████╗░░██████╗
# ████╗░██║██╔══██╗██╔══██╗██║██║░░░░░╚██╗░██╔╝██╔══██╗██╔════╝░██║░░██╗░░██║██╔══██╗██╔══██╗██╔══██╗██╔════╝
# ██╔██╗██║██║░░██║███████║██║██║░░░░░░╚████╔╝░██████╔╝█████╗░░░╚██╗████╗██╔╝███████║██████╔╝██║░░██║╚█████╗░
# ██║╚████║██║░░██║██╔══██║██║██║░░░░░░░╚██╔╝░░██╔══██╗██╔══╝░░░░████╔═████║░██╔══██║██╔══██╗██║░░██║░╚═══██╗
# ██║░╚███║██████╔╝██║░░██║██║███████╗░░░██║░░░██║░░██║███████╗░░╚██╔╝░╚██╔╝░██║░░██║██║░░██║██████╔╝██████╔╝
# ╚═╝░░╚══╝╚═════╝░╚═╝░░╚═╝╚═╝╚══════╝░░░╚═╝░░░╚═╝░░╚═╝╚══════╝░░░╚═╝░░░╚═╝░░╚═╝░░╚═╝╚═╝░░╚═╝╚═════╝░╚═════╝░

# Discord server: https://discord.gg/qNyybSSPm5
# Modrinth: https://modrinth.com/plugin/ndailyrewards

# General settings
check-updates: true

# Database configuration
database:
  # Select here the database you want to use
  # The following databases are supported:
  #  - sqlite - (default) stores all data in a local file
  #  - mariadb - allows using a remote database
  type: sqlite

  # SQLite configuration
  sqlite:
    file: "ndailyrewards.db"
  # MariaDB configuration
  mariadb:
    jdbc: "jdbc:mariadb://localhost:3306/ndailyrewards"
    username: "root"
    password: "password"

  # Advanced configuration for Database (do not touch unless you know what you are doing)
  # Comment out any data source property to disable setting it.
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048
  useServerPrepStmts: true
  useLocalSessionState: true
  rewriteBatchedStatements: true
  cacheResultSetMetadata: true
  cacheServerConfiguration: true
  elideSetAutoCommits: true
  maintainTimeStats: false

# Player events
events:
  # Whether a reward should automatically claim when a player joins (if available)
  auto-claim-reward: false
  # Delay in seconds before the reward is automatically claimed
  auto-claim-delay: 10
  # When player joins the server, should plugin open the reward GUI?
  open-gui-when-available: false
  # When player joins the server, should plugin notify player about available rewards?
  notify-when-available: true

# Rewards configuration
rewards:
  # When a player reaches the day limit, should it reset to the first day?
  reset-when-all-claimed: true
  # When player joins server for the first time, should the reward be available?
  first-join-reward: false
  # Specify how many days the player has to wait to claim the reward again (in hours)
  cooldown: 24
  # Specify the time for which the rewards will be reset if the player has not collected the reward (in hours)
  reset-time: 24
  # Should next day unlock after midnight?
  unlock-after-midnight: false
  # Available actions:
  # [console] - entered statement will be executed from console
  # [player] - statement performed as player command execution
  # [message] - messages the player with specified text
  # [actionbar] - shows the text in actionbar for the player
  # [title] - sends primary title with entered text
  # [subtitle] - sends secondary title with entered text
  # [sound] - plays specified sound for the player (sound:volume:pitch)
  # [permission] {ndailyrewards.permission} - checks if player has permission
  # [luck] {0-100} - executes the statement with a specified chance (0-100)
  # [close] - closes the inventory for the player
  # You can also use PlaceholderAPI placeholders (requires PlaceholderAPI plugin)
  # Note: First slot in inventory is 0, not 1
  days:
    '1':
      position: 10
      lore:
        - "&7&lRewards:"
        - "&6- &e1x &6Diamond"
      actions:
        - "[console] give <player> diamond 1"
        - "[message] &6You have claimed your reward!"
        - "[sound] ENTITY_EXPERIENCE_ORB_PICKUP:1:1"
    '2':
      position: 11
      lore:
        - "&7&lRewards:"
        - "&6- &e2x &6Diamond"
      actions:
        - "[console] give <player> diamond 2"
        - "[message] &6You have claimed your reward!"
        - "[sound] ENTITY_EXPERIENCE_ORB_PICKUP:1:1"
    '3':
      position: 12
      lore:
        - "&7&lRewards:"
        - "&6- &e3x &6Diamond"
      actions:
        - "[console] give <player> diamond 3"
        - "[message] &6You have claimed your reward!"
        - "[sound] ENTITY_EXPERIENCE_ORB_PICKUP:1:1"
    '4':
      position: 13
      lore:
        - "&7&lRewards:"
        - "&6- &e4x &6Diamond"
      actions:
        - "[console] give <player> diamond 4"
        - "[message] &6You have claimed your reward!"
        - "[sound] ENTITY_EXPERIENCE_ORB_PICKUP:1:1"
    '5':
      position: 14
      lore:
        - "&7&lRewards:"
        - "&6- &e5x &6Diamond"
      actions:
        - "[console] give <player> diamond 5"
        - "[message] &6You have claimed your reward!"
        - "[sound] ENTITY_EXPERIENCE_ORB_PICKUP:1:1"
    '6':
      position: 15
      lore:
        - "&7&lRewards:"
        - "&6- &e6x &6Diamond"
      actions:
        - "[console] give <player> diamond 6"
        - "[message] &6You have claimed your reward!"
        - "[sound] ENTITY_EXPERIENCE_ORB_PICKUP:1:1"
    '7':
      position: 16
      lore:
        - "&7&lRewards:"
        - "&6- &e7x &6Diamond"
      actions:
        - "[console] give <player> diamond 7"
        - "[message] &6You have claimed your reward!"
        - "[sound] ENTITY_EXPERIENCE_ORB_PICKUP:1:1"

gui:
  reward:
    title: "&6Daily Rewards"
    size: 27
    display:
      available:
        material: "EMERALD_BLOCK:1"
        name: "&aDay <dayNum>"
        lore:
          - "&7Your Reward Awaits"
          - "&7Click Me to claim your prize!"
          - ""
          - "<reward-lore>"
      claimed:
        material: "COAL_BLOCK:1"
        name: "&aDay <dayNum>"
        lore:
          - "&7You have claimed this reward"
          - ""
          - "<reward-lore>"
      next:
        material: "COAL_BLOCK:1"
        name: "&aDay <dayNum>"
        lore:
          - "&7Your Reward Will Be Here Soon"
          - "&7Wait <time-left>"
          - ""
          - "<reward-lore>"
      unavailable:
        material: "BARRIER:1"
        name: "&aDay <dayNum>"
        lore:
          - "&7You have not reached this day yet"
          - ""
          - "<reward-lore>"
      filler:
        enable: true
        material: "GRAY_STAINED_GLASS_PANE:1"
        name: "&7"
        lore: [ ]

    # Custom GUI items
    custom: [ ]

sound:
  open:
    enabled: true
    type: "BLOCK_BARREL_OPEN:1:1"