# ███╗░░██╗██████╗░░█████╗░██╗██╗░░░░░██╗░░░██╗██████╗░███████╗░██╗░░░░░░░██╗░█████╗░██████╗░██████╗░░██████╗
# ████╗░██║██╔══██╗██╔══██╗██║██║░░░░░╚██╗░██╔╝██╔══██╗██╔════╝░██║░░██╗░░██║██╔══██╗██╔══██╗██╔══██╗██╔════╝
# ██╔██╗██║██║░░██║███████║██║██║░░░░░░╚████╔╝░██████╔╝█████╗░░░╚██╗████╗██╔╝███████║██████╔╝██║░░██║╚█████╗░
# ██║╚████║██║░░██║██╔══██║██║██║░░░░░░░╚██╔╝░░██╔══██╗██╔══╝░░░░████╔═████║░██╔══██║██╔══██╗██║░░██║░╚═══██╗
# ██║░╚███║██████╔╝██║░░██║██║███████╗░░░██║░░░██║░░██║███████╗░░╚██╔╝░╚██╔╝░██║░░██║██║░░██║██████╔╝██████╔╝
# ╚═╝░░╚══╝╚═════╝░╚═╝░░╚═╝╚═╝╚══════╝░░░╚═╝░░░╚═╝░░╚═╝╚══════╝░░░╚═╝░░░╚═╝░░╚═╝░░╚═╝╚═╝░░╚═╝╚═════╝░╚═════╝░
# Created by NONPLAY & BX-Team - https://github.com/BX-Team

# CurseForge: https://www.curseforge.com/minecraft/bukkit-plugins/ndailyrewards
# Source Code: https://github.com/BX-Team/NDailyRewards
# Material names: https://minecraft.fandom.com/wiki/Materials#Materials
# Support server: https://discord.gg/9K4zWX96gx

data:
  auto-save: 15
  storage:
    type: sqlite #sqlite or MySQL
    username: none
    password: none
    host: none
    database: none
  purge:
    enabled: false
    days: 60
options:
  auto-open:
    enabled: true
    only-when-have: true
  days-row: 7
  rewards-cooldown: 86400
  unlock-after-midnight: false
rewards:
  '1':
    lore:
      - '&7Come back every day to'
      - '&7receive even better rewards!'
      - ''
      - '&e&lRewards:'
      - '&6- $500'
      - '&6- x2 Diamonds'
    commands:
      - 'console: eco give %player% 500'
      - 'console: give %player% diamond 2'
    messages:
      - '&aCongratulations! You got reward for join %day%st day in a row!'
  '2':
    lore:
      - '&7Come back every day to'
      - '&7receive even better rewards!'
      - ''
      - '&e&lRewards:'
      - '&6- $1500'
      - '&6- x4 Diamonds'
    commands:
      - 'console: eco give %player% 1500'
      - 'console: give %player% diamond 2'
    messages:
      - '&aCongratulations! You got reward for join %day%nd day in a row!'
  '3':
    lore:
      - '&7Come back every day to'
      - '&7receive even better rewards!'
      - ''
      - '&e&lRewards:'
      - '&6- $3500'
      - '&6- x8 Diamonds'
    commands:
      - 'console: eco give %player% 3500'
      - 'console: give %player% diamond 8'
    messages:
      - '&aCongratulations! You got reward for join %day%rd day in a row!'
  '4':
    lore:
      - '&7Come back every day to'
      - '&7receive even better rewards!'
      - ''
      - '&e&lRewards:'
      - '&6- $5000'
      - '&6- x16 Diamonds'
      - '&6- 10 Exp Levels'
    commands:
      - 'console: eco give %player% 5000'
      - 'console: give %player% diamond 16'
      - 'console: exp give %player% 10l'
    messages:
      - '&aCongratulations! You got reward for join %day%th day in a row!'
  '5':
    lore:
      - '&7Come back every day to'
      - '&7receive even better rewards!'
      - ''
      - '&e&lRewards:'
      - '&6- $5000'
      - '&6- x16 Diamonds'
      - '&6- 20 Exp Levels'
    commands:
      - 'console: eco give %player% 5000'
      - 'console: give %player% diamond 16'
      - 'console: exp give %player% 20l'
    messages:
      - '&aCongratulations! You got reward for join %day%th day in a row!'
  '6':
    lore:
      - '&7Come back every day to'
      - '&7receive even better rewards!'
      - ''
      - '&e&lRewards:'
      - '&6- $5000'
      - '&6- x16 Diamonds'
      - '&6- 30 Exp Levels'
    commands:
      - 'console: eco give %player% 5000'
      - 'console: give %player% diamond 16'
      - 'console: exp give %player% 30l'
    messages:
      - '&aCongratulations! You got reward for join %day%th day in a row!'
  '7':
    lore:
      - '&7Come back every day to'
      - '&7receive even better rewards!'
      - ''
      - '&e&lRewards:'
      - '&6- $10000'
      - '&6- x16 Diamonds'
      - '&6- 40 Exp Levels'
    commands:
      - 'console: eco give %player% 10000'
      - 'console: give %player% diamond 16'
      - 'console: exp give %player% 40l'
    messages:
      - '&aCongratulations! You got reward for join %day%th day in a row!'
gui:
  title: '&d&lDaily Rewards!'
  size: 27
  days-positions: '10,11,12,13,14,15,16'
  days-display:
    available:
      material: 'EMERALD_BLOCK:0:1'
      name: '&a[Day #%day%] &fAvailable Reward!'
      lore:
        - '%reward-lore%'
        - ''
        - '&a» &7Expires in: &a%expire%'
        - '&aClaim it right now!'
    taken:
      material: 'COAL_BLOCK:0:1'
      name: '&7[Day #%day%] &8Taken Reward'
      lore:
        - '%reward-lore%'
        - ''
        - '&8» &7Reward taken.'
    locked:
      material: 'REDSTONE_BLOCK:0:1'
      name: '&c[Day #%day%] &7Locked Reward'
      lore:
        - '%reward-lore%'
        - ''
        - '&c» &7Claim the previous reward to unlock!'
    next:
      material: 'GOLD_BLOCK:0:1'
      name: '&e[Day #%day%] &7Awaiting...'
      lore:
        - '%reward-lore%'
        - ''
        - '&e» &7Available in: &e%time%'
  items:
    panes:
      material: BLUE_STAINED_GLASS_PANE
      name: '&b[Daily Rewards]'
      enchanted: false
      lore:
        - '&7Come back every day to receive'
        - '&7your daily bonus!'
        - ''
        - '&aThe more days in a row you'
        - '&ajoin the better the reward!'
        - ''
        - '&cYou must wait: &7%time%'
        - '&cbefore claiming your next bonus'
      slots: 0,1,2,3,4,5,6,7,8,9,17,18,19,20,21,22,23,24,25,26

# DO NOT CHANGE THIS
cfgver: '1.2'