name: NDailyRewards
version: '${version}'
main: space.bxteam.ndailyrewards.NDailyRewards
loader: space.bxteam.ndailyrewards.NDailyRewardsLoader
api-version: '1.19'
authors: [NONPLAYT]
description: Reward players for playing on your server
