name: NDailyRewards
version: '${version}'
main: org.bxteam.ndailyrewards.NDailyRewards
api-version: '1.16'
authors: [NONPLAYT]
website: https://github.com/BX-Team/NDailyRewards
description: Reward players for playing on your server
softdepend:
  - PlaceholderAPI
commands:
  reward:
    aliases: [rw]
permissions:
  ndailyrewards.claim:
    default: true
  ndailyrewards.help:
    default: true
  ndailyrewards.reload:
    default: op
  ndailyrewards.setday:
    default: op
  ndailyrewards.version:
    default: op
