name: NDailyRewards
version: '${project.version}'
main: gq.bxteam.ndailyrewards.NDailyRewards
api-version: 1.13
softdepend: [ Citizens ]
authors: [ NONPLAY, Xenolit ]
description: Reward players for playing on your server!
website: https://discord.gg/p7cxhw7E2M
commands:
  ndailyrewards:
    aliases: [rewards, ndailyreward, dailybonus, ndr]
    description: Main command
permissions:
  ndailyrewards.user:
    description: Allows players to use non-admin commands.
    default: true
  ndailyrewards.admin:
    description: Allows to use admin commands.
    default: op