blank_issues_enabled: true
contact_links:
  - name: ByteBin
    url: https://bin.bxteam.org
    about: Use this link to paste your code if you are open a issue
  - name: Discord Support Server
    url: https://discord.gg/qNyybSSPm5
    about: Our support Discord, please ask questions and seek support here. RU and EN support