blank_issues_enabled: false
contact_links:
  - name: BPaste
    url: https://paste.bxteam.gq
    about: Use this link to paste your code if you are open a issue!
  - name: Discord Support Server
    url: https://discord.gg/9K4zWX96gx
    about: Our support Discord, please ask questions and seek support here. RU and EN support