name: Feature request
description: Suggest an idea for NDailyRewards
labels: '🔧 feature'

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request for NDailyRewards! Fill out the following form to your best ability to help us understand your feature request and greately improve the change of it getting added.

  - type: textarea
    attributes:
      label: What feature do you want to see added?
      description: A clear and concise description of your feature request.
    validations:
      required: true