name: Java CI with Maven

on:
  push:
  pull_request:
    branches: [ master ]
    
permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Make Gradlew executable
      run: chmod +x ./gradlew
    - name: Query Version
      run: |
        echo "::set-output name=VERSION_NAME::$(${{github.workspace}}/gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')"
      id: fetch-version
    - name: Get Version
      run: |
        echo "version_name=${{steps.fetch-version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Upload to Modrinth (Alpha)
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: ZiFzQAnz
        modrinth-featured: false
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        modrinth-dependencies: |
          nfGCP9fk@2.11.3(required)
        files: "build/libs/NDailyRewards-${{steps.fetch-version.outputs.VERSION_NAME}}.jar"
        version-type: alpha
        name: NDailyRewards v${{ env.version_name }}
        version: ${{ env.version_name }}
        game-version-filter: releases
        changelog: ${{ github.event.head_commit.message }}
        loaders: |
          bukkit
          spigot
          paper
          purpur
        game-versions: |
          [1.16,1.20)
        fail-mode: fail
        java: 17
    - name: Upload NDailyRewards
      uses: actions/upload-artifact@v3.1.2
      with:
        name: NDailyRewards Dev Artifacts
        path: "build/libs/NDailyRewards-*.jar"
