# Builds the project with Gradle and uploads to Modrinth with alpha tag when a commit is pushed to master.
name: Java CI with Gradle

on:
  push:

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Make Gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.8.0
      with:
        arguments: build
    - name: Upload NDailyRewards
      uses: actions/upload-artifact@v3.1.3
      with:
        name: NDailyRewards Dev Artifacts
        path: "build/libs/NDailyRewards-*.jar"
