# Builds the project with Gradle and uploads the artifact to the GitHub Actions Artifacts.
name: Java CI with Gradle

on:
  push:

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Make Gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3.4.2
      with:
        arguments: build

    #- name: Publish API
    #  continue-on-error: true
    #  uses: gradle/gradle-build-action@v3.4.2
    #  with:
    #    arguments: publish -PndailyrewardsUsername=${{ secrets.REPO_USERNAME }} -PndailyrewardsPassword=${{ secrets.REPO_SECRET }}

    #- name: Upload NDailyRewards
    #  uses: actions/upload-artifact@v4.3.3
    #  with:
    #    name: NDailyRewards Dev Artifacts
    #    path: "build/libs/NDailyRewards-*.jar"
