name: Deploy NDailyRewards

on:
  release:
    types: [published]

permissions:
  contents: read
  checks: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Extract Version Number
      id: version
      run: |
        VERSION=${{ github.event.release.tag_name }}
        VERSION=${VERSION#v}
        echo "version=${VERSION}" >> $GITHUB_OUTPUT

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make Gradlew executable
      run: chmod +x ./gradlew

    - name: Publish API
      continue-on-error: true
      run: ./gradlew api:publish
      env:
        REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
        REPO_PASSWORD: ${{ secrets.REPO_SECRET }}

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to Modrinth
      uses: WiIIiam278/mc-publish@hangar
      with:
        modrinth-id: 'ZiFzQAnz'
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        modrinth-featured: true
        modrinth-unfeature-mode: 'any'

        hangar-id: BX-Team/NDailyRewards
        hangar-token: ${{ secrets.HANGAR_TOKEN }}

        files: 'build/libs/NDailyRewards-*.jar'

        name: 'NDailyRewards ${{ steps.version.outputs.version }}'
        version: ${{ steps.version.outputs.version }}
        version-type: 'release'
        changelog: ${{ github.event.release.body }}

        loaders: |
          paper
          purpur
          folia
          spigot
        game-versions: |
          1.16
          1.16.1
          1.16.2
          1.16.3
          1.16.4
          1.16.5
          1.17
          1.17.1
          1.18
          1.18.1
          1.18.2
          1.19
          1.19.1
          1.19.2
          1.19.3
          1.19.4
          1.20
          1.20.1
          1.20.2
          1.20.3
          1.20.4
          1.20.5
          1.20.6
          1.21
          1.21.1
          1.21.2
          1.21.3
          1.21.4
          1.21.5
          1.21.6
          1.21.7
          1.21.8
        java: 17
