name: Java CI with Maven

on:
  push:
    branches:
      - *
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload NDailyRewards
      uses: actions/upload-artifact@v3.1.2
      with:
        name: NDailyRewards Dev Artifacts
        path: "target/*ndailyrewards*.jar"