name: Publish NDailyRewards
on:
  release:
    types: [ published ]

permissions:
  contents: read
  checks: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v4

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make Gradlew executable
      run: chmod +x ./gradlew

    - name: Publish API
      continue-on-error: true
      run: ./gradlew publish -PndailyrewardsUsername=${{ secrets.REPO_USERNAME }} -PndailyrewardsPassword=${{ secrets.REPO_SECRET }}