name: Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to release'
        required: true

jobs:
  set-release-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        ref: ${{ github.ref }}

    - name: Set Version
      run: |
        sed -i 's/^version=.*/version='"${{ inputs.version }}"'/g' gradle.properties

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: 'chore(release): bump version to ${{ inputs.version }}'

  publish:
    needs: set-release-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Checkout latest release tag
      id: tag_search
      run: |
        echo "latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make Gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish API
      continue-on-error: true
      run: ./gradlew api:publish
      env:
        REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
        REPO_PASSWORD: ${{ secrets.REPO_SECRET }}

    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v5
      with:
        mode: COMMIT
        fromTag: ${{ steps.tag_search.outputs.latest_tag }}
        toTag: ${{ github.ref }}
        configuration: ".github/changelog_configuration.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release to GitHub
      uses: softprops/action-gh-release@v2.3.2
      with:
        body: ${{ steps.github_release.outputs.changelog }}
        tag_name: v${{ inputs.version }}
        generate_release_notes: false
        draft: false
        prerelease: false
        target_commitish: master
        token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_unmatched_files: true
        name: NDailyRewards ${{ inputs.version }}
        preserve_order: true

    - name: Release to Modrinth and Hangar
      uses: WiIIiam278/mc-publish@hangar
      with:
        modrinth-id: 'ZiFzQAnz'
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        modrinth-featured: true
        modrinth-unfeature-mode: 'any'

        hangar-id: BX-Team/NDailyRewards
        hangar-token: ${{ secrets.HANGAR_TOKEN }}

        files: 'build/libs/NDailyRewards-*.jar'

        name: 'NDailyRewards ${{ inputs.version }}'
        version: ${{ inputs.version }}
        version-type: 'release'
        changelog: ${{ steps.github_release.outputs.changelog }}

        loaders: |
          paper
          purpur
          folia
          spigot
        game-versions: |
          1.16
          1.16.1
          1.16.2
          1.16.3
          1.16.4
          1.16.5
          1.17
          1.17.1
          1.18
          1.18.1
          1.18.2
          1.19
          1.19.1
          1.19.2
          1.19.3
          1.19.4
          1.20
          1.20.1
          1.20.2
          1.20.3
          1.20.4
          1.20.5
          1.20.6
          1.21
          1.21.1
          1.21.2
          1.21.3
          1.21.4
          1.21.5
          1.21.6
          1.21.7
          1.21.8
        java: 17
